### ISSUE TITLE
extend number of grocery lists

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar-fetch#149]
- [ x ] Read intro article: 
- [ ] discussion at Trello task: https://trello.com/c/TDNcWeCB/31-extend-number-of-grocery-lists-by-moving-data-that-i-put-into-folder-grocery-lists-i-think-we-dont-need-to-move-it-in-bulik-mayb
- [ ] fork our repository
- [ ] move files from https://github.com/GroceriStar/groceristar-fetch/tree/master/grocery-lists
to https://github.com/GroceriStar/groceristar-fetch/tree/master/data/Grocery
and connect with departments and ingredients

Current db schema: https://groceristar.github.io/documentation/docs/schema.html
[Big version](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-LFjxLdVW05N5PW6VTr3%2F-LG8YeUBnTuAAqX3HtAS%2F-LG8YthwFVPzSIwJ-2uW%2FGroceristar%20%20%20SqlDBM.png?alt=media&token=3943f963-3659-4e4f-81f7-cc7d58468bf1)

**Comment by atherdon** [comment]
@kraftaa Wow! You did a great research. this is what i wanted from you.

> 1) moving files - does it mean changing folders in github repository?
yep. that data right now didn't connected with our js methods (data from folder "grocery-lists") - I mean we cannot get access to it from the outside. When you'll move this data - we'll delete that folder.

> 2.1 So do we have 6 ingredients in one row or 1(Beans)?
We have one department(Beans) and an array of 6 ingredients - connected with this department.
2.2 Item right now is equal to Ingredient. but at the next stages - grocery list will have a direct connection with Items(right now we connect with Ingredients). Items will consist - quantity, measurement,  ingredient/product name. and next item will also have a price. 
more information here: https://medium.com/groceristar/database-schema-of-groceristar-current-release-20dc1b4be7b9
I have more data about schemes but don't want dump everything on you right now.

2.3 many departments ...  ```"id":1 "Fresh vegetables", "id":2 "VEGGIES", "id":3 "VEGETABLES" ```
you right - this rows are duplicates. maybe later we'll clean it up. Our problem - we have a few grocery list templates, and we didn't really check this so far. It'll be cool if you can create a separated issue on github - so we don't forget about it. nice catch, btw!
I think for this case - you should add to "Fresh vegetables", because in an ideal world - it'll be our main department.

> 4. briefly - this static data related to our another bigger project(ChickenKyiv). So recipes structure didn't match with our GS database schema. 
And as you can see - instead of `department_id` it has `category_id` but this is not an accurate name, because usually, recipes can have user-defined categories, like tags (child-friendly, easy-to-do). And we use that data in order to make our react components less related to database structure... 

sorry for misleading you - this was done and I don't catch it myself. Btw, you can create a separate issue at github too, so we didn't forget about it too.

---

Just rechecked data that you should move - sometimes it didn't have departments at all.
it's a dirty solution, but assign them an 'Other' category for now. Because right now we can only update it by hands, but this is a stupid approach. we also have an ML team - they will help us later with department assignment automatically.

Btw - the reason why I assign this task to you - we're mastering your vision in complex structures - aka collections. it'll handy later - when you'll work with data, received from the server.

---

if you already forked this repo, and start to work on it - feel free to submit some unfinished results via pull requests - but add notes what document i should compare with results. i think we'll be able to handle this task quickly together

**Comment by kraftaa** [comment]
I've added new ingredients to the departments from the array id:1 in grocery.json
pull check failed as each object has to have property `departments`.
I got confused where these ingredients have to be added -inside first array or just additional 1 dict with all new arrays inside.
Could you please have a look at my file in the fork:
https://github.com/kraftaa/groceristar-fetch/blob/master/data/Grocery/grocery.json

**Comment by atherdon** [comment]
ok, will check it right now.

**Comment by atherdon** [comment]
i understand why you're confused :)
it's not an easy put cool task for js developer.
let me show you how I would do this task
https://www.useloom.com/share/1cc82ed133804aff92435933339a4d9e

i also start to thinking that maybe i can make this task easier - by applying clear format for this shop lists... because right now i think it's not an easy task to differentiate departments/ingredients...

**Comment by atherdon** [comment]
@kraftaa buzz me if something will be not clear

**Comment by kraftaa** [comment]
thank you for the video, really appreciate it.
I understand the idea, but still can't get how to combine ingredients -they are so overlapping and would create (sorry if I'm wrong) a weird shopping list due to inconsistent list of ingredients.
I mean: in video we have ingredients "Beans" , department "Other"
but in fact it's legumes and "Beans" by itself would have an array of different variety of beans.
And `.md` files also include some recipes like `toasted bagel with ...` - it can't be added as ingredient.

I mean there are has to be a database with list of main departments like "Produce", "Dairy", "Meat", "Poultry", "Fish", "Bulk", "Office", "Other" etc (example)
then inside "Produce" we have "Fruits", "Vegetables",
inside "Fruits" we have "Apples", inside "Apples"  we have different ingredients -kinds of apples.
Could be properties like "organic", "conventional".
So all recipes and diets are taking the same ingredients from the same base.
There should be additional properties describing the cooking/conditioning process, but we can't mix up inconsistent items, as it would backfire at the moment we would like to use it.
And I believe database have to be one for ingredients with tags describing diets, diff shopping lists etc, but we have to have the same ingredients to be available for each diet and shopping preferences.

I see how it's done by Wegmans, this is what I wanted to say:
https://www.wegmans.com/products

What do you think?
thank you!

**Comment by atherdon** [comment]
i totally agree with your points.
and yeah - overlapping ingredients it's a big problem(but it can be solved in a programmable way).

---

so tell me what we should do. because i have a lot of details about how to extend this database - and your points 100% correct. but I don't want to do it myself :) we can continue this conversation and explore different ways that will help us to make this module better and easy to use or we can move it to separated place - because I'm sure that this is hard to solve. 

---

I actually preparing another article - that will explain reasons of creating this package - so it'll give you more details.

---

quick question - do you think we have an issue of connecting grocery lists and ingredients - am i right?

I didn't review code of this module quite a while. Admin of this repo is Vadim - my first and only one Ukrainian student. So maybe some of changes, that was done by our interns team didn't work as they should or as i assumed. 

---

and as I see that you're interested in "database architecture" - i'll make a note and will try later to cultivate it. 

---

i think it's a right time to share some more articles with you :)
https://medium.com/groceristar/chickenkyiv-database-logic-intro-part-1-b2c449d92aa3
https://medium.com/groceristar/chickenkyiv-database-logic-simple-samples-part-2-1ee3ccc6b3d
https://medium.com/groceristar/chicken-kyiv-recipe-db-schema-part3-b80f33ec5d96

**Comment by kraftaa** [comment]
thank you!
I'll have a look again at data and will try to express my ideas.
And thank you for the links!

**Comment by kraftaa** [comment]
Hi Arthur,
thank you for the links!
Sorry for not answering right away - now it's Christmas time with all hectic and crazy stuff :)
I've been thinking that I see schema like that- sorry it's very basic,
but the main thing is ingredient which is linked to all other tables which have different departments, menus, diet plans, organic or not, high in carbs, fat, available here or there

https://docs.google.com/drawings/d/15onIOb0bVRYmUOQC8yI86F-EodCu0kjkPRCMyCkJ8SQ/edit?usp=sharing

I don't know how it could be done in JS I think JS has to be used to connect but the database should not be in JS  itself but either MongoDB or PostgreSQL. 
MongoDB is used by Facebook, not sure if it affects how it works with React, but looks like there are options for both DB.
I just really think we can't do app with many diff databases, picking up items from diff files. 
Finally we are working with the same ingredients, just combining them differently ( I think so).
Otherwise we'd get stuck very soon and it would limit our ability to use the app.
I've found few tutorials 
http://zetcode.com/db/mongodbjavascript/
https://www.w3schools.com/nodejs/nodejs_mongodb_query.asp
https://medium.com/@orbmancer/you-know-javascript-store-stuff-with-a-database-87d13e4a5e3d
https://www.guru99.com/node-js-mongodb.html

will give them a try to understand how it works.
Would also check options for PostgreSQL (which has keys, but looks like MongoDB is more popular option)
If I get it(i mean when I get it:) I could try to use it on for example wegmans list (the grocery store, I've sent you link in previous article), won't have all details but will have fields for them.

**Comment by atherdon** [comment]
working on the long reply to you.
just briefly:
- I like your schema, but it can be improved.
- we're using MongoDB but maybe later we'll switch to DynamoDB(pretty similar, but it's backed by Amazon with other good features...)

more info soon

**Comment by atherdon** [comment]
@kraftaa i think we should continue this task as it is for this moment. Let's put new grocery objects into grocery,json, departments to departments and ingredients at separated files.
when i'll finish my article - you'll be able to have more data and we'll be able to think about a better.
right now the goal is to reduce amount of tasks for this module.


btw, just to let you know - this is actually the easiest part of our projects - and when you'll feel ok with a logic of this module - we'll move you to some other tasks...

**Comment by atherdon** [comment]
Btw, you can preview how actually we're using our fetch plugin with section, related to grocery lists at our showcase repo: https://github.com/GroceriStar/showcase
deployed website: https://boring-benz-76e55f.netlify.com/
hope this will help

**Comment by kraftaa** [comment]
hi Arthur,
thank you,
nice react app! 
I have couple of questions:
1)  `Dairy` but also `Cheese` which is diary and they are different departments while different cheese ingredients are in `Cheese` department which is in `Diary` department. If we want this app to be useful - people won't bother themselves looking for item in different departments, I believe users tend to be as lazy as possible and whoever answer this approach gets users.

2)
I'm looking at ingredients in `.md` files.
What about ingredients like that (it has `department: 1-Week Healthy Budget Grocery List` but it also has subdepartments  as fruit ,vegetables, grains:
```
1-Week Healthy Budget Grocery List
Fruit
4 pounds Apples 6 pounds Bananas 1 pound Blueberries, frozen 2 1/2 pounds Any In-Season Fruit (aim for $1.50/lb) 2 Lemons 6 oz Raisins

Vegetables
4 Avocados 1/3 pound Broccoli, frozen organic 4 pounds Carrots, organic 3/4 pounds Celery 1 bunch Kale 3/4 pound Corn, frozen organic 2 cans Diced Tomatoes, organic 1 head Garlic 1 1/4 pound Green Beans, frozen organic 1 pound Lettuce or Salad Mix, organic 1 small can Mushrooms 3 pounds Potatoes 1 16-oz jar Salsa 10 oz Spinach 4 large Sweet Potatoes, organic 1 pound Tomatoes 1/2 pound Zucchini 1 6-oz can Olives, sliced 1 pound Onion, yellow

Grains
11 6-inch Corn Tortillas 22 Slices Bread, gluten free 2 pounds Brown Rice Flour, organic 1/2 `

so 
```
`1-Week Healthy Budget Grocery List` is the name of `.json` file and `Fruits`, `Vegetables` etc it's departments?

3. Are there any rules about using capital letters in departments' names?

thanks!

**Comment by atherdon** [comment]
@kraftaa you are raising a lot of good and important questions!
1. Cheese is an ingredient at Dairy department.
(briefly. but we actually have a completed database for dairy products with a really cool classification. but i'm not sure if we are ready to use it in our current situation) 
---

Again - i understand your concerns, but with limited resources - it's hard to keep eye on everything. We can do it that way - if you wish - you can make a big step forward and adjust the structure of this grocery lists as you wish and as you think it's necessary. Or i'll be fine to just have a GL that we can import to db right now. Because these troubles will be only growing when we'll have more data. LIke if we have this issues with 5-10 lists - how much issues we'll have with 50 lists? I like your notes, and i'll keep them - because they will be important when our ML team will finish(it's done), test(partially), format(not completed) a script that will use image recognition for grocery lists from Pinterest

---

2. Quick question - when i look on example that you've shared - i think you don't edit the .md file, right?
Reason why i'm asking - if you click edit on md file - you'll see that i should be better formatted. i think it's important to let you know.

For now - let's avoid subdepartments. But maybe in future when we'll have a lot of data to operate - we'll make a strict structure of products with wide departments logic. for now `Department -> Ingredient` - it's a fine relation

> 1-Week Healthy Budget Grocery List is the name of .json file and Fruits, Vegetables etc it's departments?

it's the name of json file, related to ingredients. Yes, Fruits, Vegetables are departments.

3. No rules, but again good question - should be noted! Will be important when we'll work on our import script.

**Comment by kraftaa** [comment]
Hi Arthur, thank you

I agree. better keep going than wondering about perfect structure.
No - I haven't edited `.md` files, I've just copied data from it for the question.
I think I got it, and made `.json` files with ingredients for `1.md` and updated `grocery.json` accordingly (synced fork before it).
Surprisingly when I created pull request it failed check - saying that for departments length:
 `Expected value to have length:
      7`

and I have more, so it failed. It also failed to add new `.json` files to ingredients - I really don't understand why.
Mine formatted as following: 
`
{"name": "ice", "department": "grains and flours"},
`
not
`
{
    "name": "Beans",
    "department": "Other"
  },
`
because I was adding departments by function not manually, otherwise it's a bit insane, even with functions it was tons of sublime text shortcuts and editing as all ingredients listed in different ways.

I also don't understand how to treat `meal calendar` section:
```
meal calendar
Breakfast

Oatmeal with Dried Fruit, Flax Meal, and Cinnamon
Lunch

Pasta la Caprese
Green Smoothie
Dinner

Split Pea Soup
One piece of Whole Wheat Garlic Bread
Mixed Greens Salad with Balsamic Vinaigrette
Snacks

Apple with Almond Butter (or other nut butter)


Day Two
Breakfast

High-fiber, Low-Sugar Cereal with Almond Milk and Banana
Lunch

Vegan Chili
Cornbread
Caesar Salad
Dinner
```

as it has name for the file (and department for `grocery.json`) `meal calendar`, then inside the file it has:
Department day (day one, day two etc) and inside each day it has breakfast, lunch,snack, dinner.

could you please have a look at my files at 
https://github.com/kraftaa/groceristar-fetch/tree/master/data/Ingredients
and `grocery.json` 
i think I'm missing something obvious as new files don't have any conflicts.

thank you!

**Comment by atherdon** [comment]
will take a look soon.
btw, i'll advise you to use pull requests approach instead of committing into the main repo - it will help us to prevent problems and i'll be able to view your changes in the more organized way.

**Comment by atherdon** [comment]
while i'm reviewing your changes/questions, you can help me with this #156

**Comment by atherdon** [comment]
> No - I haven't edited .md files, I've just copied data from it for the question.
check how looks data when it's edited: 
![editing groceristar fetch 1 md at master groceristar groceristar fetch](https://user-images.githubusercontent.com/1469198/50506535-15d7c800-0a82-11e9-8b89-8f3927935c67.png)

For some of lists - this version looks better than when you preview .md file

---

Btw, your request to review your changes is a perfect example about the reason of using tests. We have some tests here, but it was never a priority, so our tests didn't cover all cases. I created some tasks related to tests, maybe we'll be able to finish it together with you. Will make a note about it - for future.

---

> Surprisingly when I created pull request it failed check - saying that for departments length:
Expected value to have length: 7

this is an actually how tests working and can prevent us from making mistakes. But in our current tests - we have an old statement. Before you start to increase the number of grocery lists - we have only 7 items - and we hardcode this number into tests(quick solution). this is why you got an issue. and this is why pull requests are matter - because we can address each problem at separated "space". I think also this is a reason why you push into the repo avoiding pull request flow.

**Comment by atherdon** [comment]
hold on. i think github notifications misguided me. let's keep it on pause while i'm figuring it out

**Comment by atherdon** [comment]
in case that you interested - this is one of the tasks, related to tests: #102

**Comment by kraftaa** [comment]
Thank you, agree tests are great tools.
I'll have a look at the issues.
Thank you
Ps: doing github tutorial again thanks fo teaching me!

**Comment by atherdon** [comment]
no problem! still reviewing your code.
Btw, it was not your fault. I was misled by email from GitHub. You did it fine. @kraftaa

**Comment by atherdon** [comment]
1. in order to run tests(and receive an error that we got from build at our PR) you need to run `yarn run test`
2. i moved away function, that related to your build issue. please check a static-files.test.js
we just hardcoded the values of size of arrays that we have in our static files, in order to be aware - when something will be changed. 
3. in order to update count - you need to run `yarn run playground` - it's a script for testing methods that we're building at GS section. i make it more clear - you'll get it.

---

btw, right now we have some fails in tests, because of my code. will fix it soon today.

---

i updated .md files, so now it's formated better and will save some time for you

**Comment by atherdon** [comment]
pushed updates - buzz me if you have questions

**Comment by kraftaa** [comment]
thanks,
I've looked at `staticFiles.test.js` and I see
```
  const groceryCount    = 8;
  const userCount       = 3;
```
what is it?

I've also looked at `grocerystar.test.js` and see the limit about array's count:
```
test("getGroceryById()", () => {
    for (let i = 1; i <= 7; i++) {
      var stream = groceristar.getGroceryById(i);
      expect(stream).not.toBe("");
    }
  });
```

I've run `yarn run test` and got
```
Details:

    C:\Users\Maria\Documents\GitHub\groceristar-fetch\projects\GroceriStar\groceristar.js:118
        ...item
        ^^^

    SyntaxError: Unexpected token ...

    > 1 | const groceristar = require("./groceristar.js");
        |                                                ^
      2 |
      3 | // @TODO separate methods, related to different datasets.
      4 | // So methods related to ingredients should have a

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (projects/GroceriStar/groceristar.test.js:1:48)

Test Suites: 2 failed, 3 passed, 5 total
Tests:       23 passed, 23 total
Snapshots:   0 total
Time:        5.375s
Ran all test suites.
error Command failed with exit code 1.
```
I'm a bit confused how can I fixed it.
 thank you

**Comment by atherdon** [comment]
@kraftaa hold on - i'll take a look on bugs first and then answer to your questions.
I start to touch the code at this project and everything start to tear apart :( 

I hope - you commit your last changes to your repo if you make some, right?

**Comment by kraftaa** [comment]
Right :)
No worries

**Comment by atherdon** [comment]
>> I've also looked at grocerystar.test.js and see the limit about array's count ...
perfect catch! nice "vision"

---

For the second issue please share a code link at next time, because it's hard to find a code line.

At my side i don't have issues, but this a es6/es7 feature - maybe your nodejs server didn't support it?
Read more about it here:
[simple](http://es6-features.org/#SpreadOperator)
[long explanation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

and check your nodejs version at CLI ``node -v``. I'm using 10.5.0.

---

I update an push code into your repo, related to count. You may notice that i changed variable names from camelCase into CAPS. this is the usual way to show constants, defined at the top of files/projects.
Btw, tests will crash again, because our `grocery` variable has a value equal to 8.

**Comment by atherdon** [comment]
don't worry - to be honest - es6 syntax is hard to remember and use for me too.
i has an old coding habit and sometimes I'm confused when I read some "logic structure" that was coded by someone else.

yes, you can continue to move data from .md files.
if you want -  i can just disable tests - related to count? i think it'll make the current task easier to do.

Again - you can count updated size of items at our files and update tests on your own.

tell me what do you think.

**Comment by atherdon** [comment]
- [ ] push to npm, compare results at our React projects like a showcase

**Comment by atherdon** [comment]
reviewing our conversations from this task and #153
